# Generated by Django 4.2.1 on 2023-05-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_act1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'managed': True},
        ),
    ]
