# Generated by Django 4.2.1 on 2023-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_act1', '0002_alter_studentinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
